apiVersion: v1
kind: Namespace
metadata:
  name: authapi-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: authapi-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: 154744860201.dkr.ecr.eu-north-1.amazonaws.com/auth_api:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: authapi-ns
spec:
  selector:
    app: auth-api
  ports:
  - port: 80
    targetPort: 4000
  type: ClusterIP


---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: authapi-ns
type: Opaque
data:
  # base64-encoded "mongodb://mongo-auth-service.db-ns.svc.cluster.local:27017/authdb"
  MONGO_URI: bW9uZ29kOi8vbW9uZ28tYXV0aC1zZXJ2aWNlLmRiLW5zLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2F1dGhkYg==
