apiVersion: v1
kind: Namespace
metadata:
  name: authapi-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: authapi-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: 154744860201.dkr.ecr.eu-north-1.amazonaws.com/auth_api:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-auth-service:27017/authdb"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: authapi-ns
spec:
  selector:
    app: auth-api
  ports:
  - port: 80
    targetPort: 4000
  type: ClusterIP
