apiVersion: v1
kind: Namespace
metadata:
  name: db-ns
---
apiVersion: apps/v1
kind: Deployment   #StaefulSet would be better for DB, but for demo purposes Deployment is fine
metadata:
  name: mongo-web
  namespace: db-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-web
  template:
    metadata:
      labels:
        app: mongo-web
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}   # for dev/demo only; replace with PersistentVolumeClaim later
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-web-service
  namespace: webapp-ns
spec:
  selector:
    app: mongo-web
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
