apiVersion: v1
kind: Namespace
metadata:
  name: webapp-ns
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: webapp-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: 154744860201.dkr.ecr.eu-north-1.amazonaws.com/web_app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-web-service:27017/webappdb"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: webapp-ns
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
